export const CARD_CREATED = 'CARD_CREATED';
export const CARD_SAVED = 'CARD_SAVED';
export const CARD_EDITTED = 'CARD_EDITTED';
export const CARD_DELETED = 'CARD_DELETED';

export const TITLE_CHANGED = 'TITLE_CHANGED';

export const CATEGORY_ADDED = 'CATEGORY_ADDED';
export const CATEGORY_CHANGED = 'CATEGORY_CHANGED';

export const TASK_ADDED = 'TASK_ADDED';
export const TASK_DELETED = 'TASK_DELETED';

export const CHECKBOX_CHANGED = 'CHECKBOX_CHANGED'; //category
export const TASK_CHECKBOX_CHANGED = 'TASK_CHECKBOX_CHANGED';
